In [2]:
from loguru import logger

logger.info("That's it, beautiful and simple logging!")
logger.info()

2024-03-19 21:55:57.292 | INFO     | __main__:<module>:3 - That's it, beautiful and simple logging!


In [3]:
import numpy as np
original_matrix = np.array([[0,1],[1,0]])

# 使用np.pad()函数填充原有矩阵，只填充右侧和下侧
padded_matrix = np.pad(original_matrix, pad_width=((0, 1), (0, 1)), mode='constant')
update_matrix = padded_matrix
print(update_matrix)

[[0 1 0]
 [1 0 0]
 [0 0 0]]


In [12]:
logger.info(f'\n当前的矩阵图为:\n{update_matrix}')

2024-03-19 22:00:09.528 | INFO     | __main__:<module>:1 - 
当前的矩阵图为:
[[0 1 0]
 [1 0 0]
 [0 0 0]]


In [13]:
logger.add("logs/file_{time}.log", encoding="utf-8")


1

In [14]:
logger.info(f'\n当前的矩阵图为:\n{update_matrix}')

2024-03-19 22:00:57.656 | INFO     | __main__:<module>:1 - 
当前的矩阵图为:
[[0 1 0]
 [1 0 0]
 [0 0 0]]


In [15]:
logger.info(f'\n当前的轮次为:1')

2024-03-19 22:01:21.760 | INFO     | __main__:<module>:1 - 
当前的轮次为:1


最终还是选择多个单行的f-string

In [17]:
logger.info(f'\n当前的轮次为:1'
            f'\n当前的矩阵图为:\n{update_matrix}'
            f'\n当前的节点是:node3')

2024-03-19 22:03:55.928 | INFO     | __main__:<module>:1 - 
当前的轮次为:1
当前的矩阵图为:
[[0 1 0]
 [1 0 0]
 [0 0 0]]
当前的节点是:node3


In [18]:
logger.info(f'''\n当前的轮次为:4
            \n当前的矩阵图为:\n{update_matrix}
            \n当前的节点是:node4''')

2024-03-19 22:05:32.353 | INFO     | __main__:<module>:1 - 
当前的轮次为:4
            
当前的矩阵图为:
[[0 1 0]
 [1 0 0]
 [0 0 0]]
            
当前的节点是:node4


In [20]:
logger.info(f'''\n当前的轮次为:4
            当前的矩阵图为:\n{update_matrix}
            当前的节点是:node4''')

2024-03-19 22:06:16.889 | INFO     | __main__:<module>:1 - 
当前的轮次为:4
            当前的矩阵图为:
[[0 1 0]
 [1 0 0]
 [0 0 0]]
            当前的节点是:node4
