In [1]:
import numpy

In [2]:
def generate_matrix(round):
    matrix = [[0] * round for _ in range(round)]  # 初始化矩阵所有元素为 0

In [4]:
matrix = generate_matrix(3)
print(matrix)

None


In [3]:
import numpy as np

def generate_matrix(round):
    values = np.arange(1, round + 1)
    matrix = np.outer(values, values)
    return matrix

round = 6
matrix = generate_matrix(round)
print(matrix)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [10]:
np.zeros([round,round],dtype=int)




array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [7]:
import numpy as np
round = 4
target_round =2

# 创建一个3x3的原有矩阵
original_matrix = np.array([[0, 1, 0],
                             [0, 1, 1],
                             [-1, 0, -1]])

# 使用np.pad()函数填充原有矩阵，只填充右侧和下侧
padded_matrix = np.pad(original_matrix, pad_width=((0, 1), (0, 1)), mode='constant')
update_matrix = padded_matrix
update_matrix[round-1,target_round-1]=10
# 打印填充后的新矩阵和原有矩阵
print("原有矩阵：")
print(original_matrix)
print("\n填充后的新矩阵：")
print(padded_matrix)
print("\n补充后的新矩阵")
print(update_matrix)

原有矩阵：
[[ 0  1  0]
 [ 0  1  1]
 [-1  0 -1]]

填充后的新矩阵：
[[ 0  1  0  0]
 [ 0  1  1  0]
 [-1  0 -1  0]
 [ 0 10  0  0]]

补充后的新矩阵
[[ 0  1  0  0]
 [ 0  1  1  0]
 [-1  0 -1  0]
 [ 0 10  0  0]]
