In [1]:
import numpy

In [2]:
def generate_matrix(round):
    matrix = [[0] * round for _ in range(round)]  # 初始化矩阵所有元素为 0

In [4]:
matrix = generate_matrix(3)
print(matrix)

None


In [5]:
import numpy as np

def generate_matrix(round):
    values = np.arange(1, round + 1)
    matrix = np.outer(values, values)
    return matrix

round = 5
matrix = generate_matrix(round)
print(matrix)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
